build: config - make build files close to upstream
Minimize the changes we're making to the upstream Makefile, and other
build files in scripts/config.

When doing 'make xconfig', instead of using a make variable to point to
the distro pkg-config, prepend its location to the PATH, and allow use
of plain 'pkg-config', just like it is done upstream, and here for
menuconfig, kernel_menuconfig, and kernel_nconfig.

The README file was updated to list the changes made from upstream.

Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>

diff --git a/scripts/config/Makefile b/scripts/config/Makefile
--- a/scripts/config/Makefile
+++ b/scripts/config/Makefile
@@ -1,90 +1,106 @@
 # ===========================================================================
 # OpenWrt configuration targets
-# These targets are used from top-level makefile
+
+.PHONY: clean all $(PHONY)
+all: conf mconf
+clean:
+	rm -f *.o lxdialog/*.o *.moc $(clean-files) conf mconf qconf
+
+# ===========================================================================
+# Variables needed by the upstream Makefile
+
+HOSTCC := $(CC)
+HOSTCFLAGS:= $(CFLAGS)
+CFLAGS += $(HOST_EXTRACFLAGS)
+CXXFLAGS += $(HOST_EXTRACFLAGS)
+
+kecho:=true
+
+CONFIG_SHELL:=$(SHELL)
+srctree:=.
+src:=.
+obj:=.
+Q:=$(if $V,,@)
+cmd = $(cmd_$(1))
+dot-target = $(dir $@).$(notdir $@)
+
+### Stripped down upstream Makefile follows
+# ===========================================================================
+
+# lxdialog stuff
+check-lxdialog  := $(srctree)/$(src)/lxdialog/check-lxdialog.sh
+
+# Use recursively expanded variables so we do not call gcc unless
+# we really need to do so. (Do not call gcc as part of make mrproper)
+HOST_EXTRACFLAGS += $(shell $(CONFIG_SHELL) $(check-lxdialog) -ccflags) \
+                    -DLOCALE
 
 # ===========================================================================
 # Shared Makefile for the various kconfig executables:
 # conf:	  Used for defconfig, oldconfig and related targets
-# mconf:  Used for the mconfig target.
+# mconf:  Used for the menuconfig target
 #         Utilizes the lxdialog package
 # qconf:  Used for the xconfig target
 #         Based on Qt which needs to be installed to compile it
 # object files used by all kconfig flavours
 
+lxdialog := lxdialog/checklist.o lxdialog/util.o lxdialog/inputbox.o
+lxdialog += lxdialog/textbox.o lxdialog/yesno.o lxdialog/menubox.o
 
-# Platform specific fixes
-#
-# FreeBSD
-
-check_lxdialog = $(shell $(SHELL) $(CURDIR)/lxdialog/check-lxdialog.sh -$(1))
-export CFLAGS += -DKBUILD_NO_NLS -I. $(call check_lxdialog,ccflags)
-export CXXFLAGS += -DKBUILD_NO_NLS
-
-conf-objs	:= conf.o zconf.tab.o
-mconf-objs	:= mconf.o zconf.tab.o
+conf-objs	:= conf.o  zconf.tab.o
+mconf-objs     := mconf.o zconf.tab.o $(lxdialog)
 qconf-cxxobjs	:= qconf.o
 qconf-objs	:= zconf.tab.o
 
-lxdialog-objs := \
-	lxdialog/checklist.o lxdialog/util.o lxdialog/inputbox.o \
-	lxdialog/textbox.o lxdialog/yesno.o lxdialog/menubox.o
+hostprogs-y := conf mconf qconf
 
-clean-files	:= zconf.tab.c zconf.lex.c zconf.hash.c
-# Remove qconf junk files
-clean-files	+= $(qconf-cxxobjs) qconf.moc .tmp_qtcheck qconf
+clean-files	:= qconf.moc .tmp_qtcheck
+clean-files	+= zconf.tab.c zconf.lex.c zconf.hash.c
 
-all: conf mconf
+# Check that we have the required ncurses stuff installed for lxdialog (menuconfig)
+PHONY += $(obj)/dochecklxdialog
+$(addprefix $(obj)/,$(lxdialog)): $(obj)/dochecklxdialog
+$(obj)/dochecklxdialog:
+	$(Q)$(CONFIG_SHELL) $(check-lxdialog) -check $(HOSTCC) $(HOST_EXTRACFLAGS) $(HOSTLOADLIBES_mconf)
 
-conf: $(conf-objs)
-mconf: $(mconf-objs) $(lxdialog-objs)
-	$(CC) -o $@ $^ $(call check_lxdialog,ldflags $(CC))
-qconf: $(qconf-cxxobjs) $(qconf-objs)
-ifneq ($(DISTRO-PKG-CONFIG),)
-	$(CXX) -o $@ $^ $(HOSTLOADLIBES_qconf)
-else
-	echo "You don't have 'pkg-config' installed. Cannot continue"
-	echo "For now, you may use 'make menuconfig' instead of 'make xconfig'"
-endif
+always := dochecklxdialog
 
-clean:
-	rm -f *.o lxdialog/*.o $(clean-files) conf mconf
+HOST_EXTRACFLAGS += -DKBUILD_NO_NLS
 
-zconf.tab.o: zconf.lex.c zconf.hash.c confdata.c
+# generated files seem to need this to find local include files
+HOSTCFLAGS_zconf.lex.o	:= -I$(src)
+HOSTCFLAGS_zconf.tab.o	:= -I$(src)
 
-kconfig_load.o: lkc_defs.h
+LEX_PREFIX_zconf	:= zconf
+YACC_PREFIX_zconf	:= zconf
 
-zconf.tab.c: zconf.y $(wildcard zconf.tab.c_shipped)
-zconf.lex.c: zconf.l $(wildcard zconf.lex.c_shipped)
-zconf.hash.c: zconf.gperf $(wildcard zconf.hash.c_shipped)
+HOSTLOADLIBES_qconf	= $(KC_QT_LIBS)
+HOSTCXXFLAGS_qconf.o	= $(KC_QT_CFLAGS)
 
-%.tab.c: %.y
-	cp $@_shipped $@ || bison -l -b $* -p $(notdir $*) $<
+HOSTLOADLIBES_mconf   = $(shell $(CONFIG_SHELL) $(check-lxdialog) -ldflags $(HOSTCC))
 
-%.lex.c: %.l
-	cp $@_shipped $@ || flex -L -P$(notdir $*) -o$@ $<
+$(obj)/qconf.o: $(obj)/.tmp_qtcheck
 
-%.hash.c: %.gperf
-	cp $@_shipped $@ || gperf < $< > $@
-
-ifeq ($(MAKECMDGOALS),qconf)
-qconf.o: .tmp_qtcheck
-.tmp_qtcheck: Makefile
--include .tmp_qtcheck
+# openwrt: target is qconf, not xconfig
+#ifeq ($(MAKECMDGOALS)),xconfig)
+ifeq ($(filter qconf,$(MAKECMDGOALS)),qconf)
+$(obj)/.tmp_qtcheck: $(src)/Makefile
+-include $(obj)/.tmp_qtcheck
 
 # Qt needs some extra effort...
-.tmp_qtcheck:
-	@set -e; echo "  CHECK   qt"; \
-	if $(DISTRO-PKG-CONFIG) --exists Qt5Core; then \
-	    cflags="-std=c++11 -fPIC `$(DISTRO-PKG-CONFIG) --cflags Qt5Core Qt5Gui Qt5Widgets`"; \
-	    libs=`$(DISTRO-PKG-CONFIG) --libs Qt5Core Qt5Gui Qt5Widgets`; \
-	    moc=`$(DISTRO-PKG-CONFIG) --variable=host_bins Qt5Core`/moc; \
-	elif $(DISTRO-PKG-CONFIG) --exists QtCore; then \
-	    cflags=`$(DISTRO-PKG-CONFIG) --cflags QtCore QtGui`; \
-	    libs=`$(DISTRO-PKG-CONFIG) --libs QtCore QtGui`; \
-	    moc=`$(DISTRO-PKG-CONFIG) --variable=moc_location QtCore`; \
+$(obj)/.tmp_qtcheck:
+	@set -e; $(kecho) "  CHECK   qt"; \
+	if pkg-config --exists Qt5Core; then \
+	    cflags="-std=c++11 -fPIC `pkg-config --cflags Qt5Core Qt5Gui Qt5Widgets`"; \
+	    libs=`pkg-config --libs Qt5Core Qt5Gui Qt5Widgets`; \
+	    moc=`pkg-config --variable=host_bins Qt5Core`/moc; \
+	elif pkg-config --exists QtCore; then \
+	    cflags=`pkg-config --cflags QtCore QtGui`; \
+	    libs=`pkg-config --libs QtCore QtGui`; \
+	    moc=`pkg-config --variable=moc_location QtCore`; \
 	else \
 	    echo >&2 "*"; \
-	    echo >&2 "* Could not find Qt via $(DISTRO-PKG-CONFIG)."; \
+	    echo >&2 "* Could not find Qt via pkg-config."; \
 	    echo >&2 "* Please install either Qt 4.8 or 5.x. and make sure it's in PKG_CONFIG_PATH"; \
 	    echo >&2 "*"; \
 	    exit 1; \
@@ -94,14 +110,46 @@ qconf.o: .tmp_qtcheck
 	echo "KC_QT_MOC=$$moc" >> $@
 endif
 
-#Define compiler flags to build qconf
-HOSTLOADLIBES_qconf	= $(KC_QT_LIBS)
-HOSTCXXFLAGS_qconf.o	= $(KC_QT_CFLAGS)
+$(obj)/zconf.tab.o: $(obj)/zconf.lex.c $(obj)/zconf.hash.c
 
-qconf.o: qconf.moc
-qconf.o: CXXFLAGS+=$(HOSTCXXFLAGS_qconf.o)
+$(obj)/qconf.o: $(obj)/qconf.moc
 
-moc = $(KC_QT_MOC) -i $< -o $@
+quiet_cmd_moc = MOC     $@
+      cmd_moc = $(KC_QT_MOC) -i $< -o $@
 
-%.moc: %.h .tmp_qtcheck
-	$(call moc)
+$(obj)/%.moc: $(src)/%.h $(obj)/.tmp_qtcheck
+	$(call cmd,moc)
+
+# ===========================================================================
+# OpenWrt rules and final adjustments that need to be made after reading the
+# full upstream Makefile
+
+FORCE:
+
+%.tab.c: %.y
+	bison -l -b $* -p $(notdir $*) $<
+
+%.lex.c: %.l
+	flex -L -P$(notdir $*) -o$@ $<
+
+%.hash.c: %.gperf
+	gperf < $< > $@
+
+$(foreach f, mconf.o $(lxdialog), \
+  $(eval $f: CFLAGS+=$$(HOSTCFLAGS_$f)))
+
+$(obj)/zconf.lex.o: CFLAGS += $(HOSTCFLAGS_zconf.lex.o)
+$(obj)/zconf.tab.o: CFLAGS += $(HOSTCFLAGS_zconf.tab.o)
+$(obj)/qconf.o: CXXFLAGS+=$(HOSTCXXFLAGS_qconf.o)
+
+conf: $(conf-objs)
+
+# The *conf-cfg file is used (then filtered out) as the first prerequisite to
+# avoid sourcing it before the script is built, when trying to compute CFLAGS
+# for the actual first prerequisite.  This avoids errors like:
+# '/bin/sh: ./mconf-cfg: No such file or directory'
+mconf: $(mconf-objs)
+	$(CC) -o $@ $(filter-out mconf-cfg,$^) $(HOSTLOADLIBES_mconf)
+
+qconf: $(qconf-cxxobjs) $(qconf-objs)
+	$(CXX) -o $@ $(filter-out qconf-cfg,$^) $(HOSTLOADLIBES_qconf)
